//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Школьное_расписание
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupLes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupLes()
        {
            this.Student = new HashSet<Student>();
        }
    
        public int Id { get; set; }
        public short Mo { get; set; }
        public short Tu { get; set; }
        public short We { get; set; }
        public short Th { get; set; }
        public short Fr { get; set; }
        public short Sa { get; set; }
    
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Student { get; set; }
    }
}
