//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Школьное_расписание
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int Id { get; set; }
        public short Number { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual SClass SClass { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
