//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Школьное_расписание
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container2 : DbContext
    {
        public Model1Container2()
            : base("name=Model1Container2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Schedule> ScheduleSet { get; set; }
        public virtual DbSet<Lesson> LessonSet { get; set; }
        public virtual DbSet<SClass> SClassSet { get; set; }
        public virtual DbSet<Subject> SubjectSet { get; set; }
        public virtual DbSet<Student> StudentSet { get; set; }
        public virtual DbSet<Teacher> TeacherSet { get; set; }
        public virtual DbSet<Indiv_plan> Indiv_planSet { get; set; }
        public virtual DbSet<GroupLes> GroupLesSet { get; set; }
        public virtual DbSet<PlanElem> PlanElemSet { get; set; }
    }
}
