//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Школьное_расписание
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanElem
    {
        public int Id { get; set; }
        public short Mo { get; set; }
        public short Tu { get; set; }
        public short We { get; set; }
        public short Th { get; set; }
        public short Fr { get; set; }
        public short Sa { get; set; }
        public string Type { get; set; }
    
        public virtual SClass SClass { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Indiv_plan Indiv_plan { get; set; }
    }
}
